=== Gleb-Turchik/XML_XSD_WebApp/web/resources/voucher.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.w3schools.com"
           xmlns="http://www.w3schools.com"
           elementFormDefault="qualified">

    <xs:element name="tourist-vouchers">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="voucher" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="voucher" type="Voucher" abstract="true"/>
    <xs:element name="wellness-voucher" type="Wellness" substitutionGroup="voucher"/>
    <xs:element name="entertaiment-voucher" type="Entertaiment" substitutionGroup="voucher"/>

    <xs:complexType name="Voucher">
        <xs:sequence>
            <xs:element name="type">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="weekend"/>
                        <xs:enumeration value="tour"/>
                        <xs:enumeration value="relax"/>
                        <xs:enumeration value="pilgrimage"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="country">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z][a-zA-z\s]{1,20}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="number-days-nights" type="xs:positiveInteger"/>
            <xs:element name="transport">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="air"/>
                        <xs:enumeration value="rail"/>
                        <xs:enumeration value="car"/>
                        <xs:enumeration value="liner"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="hotel-characs" type="Hotel-Characs" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="cost" type="xs:positiveInteger"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="optional" default="no-Name"/>
        <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
    </xs:complexType>
    <xs:complexType name="Hotel-Characs">
        <xs:sequence>
            <xs:element name="stars">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                        <xs:minInclusive value="1"/>
                        <xs:maxInclusive value="5"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="meal" type="xs:boolean"/>
            <xs:element name="kind-of-meal">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="false"/>
                        <xs:enumeration value="OB"/>
                        <xs:enumeration value="BB"/>
                        <xs:enumeration value="HB"/>
                        <xs:enumeration value="HB+"/>
                        <xs:enumeration value="FB"/>
                        <xs:enumeration value="FB+"/>
                        <xs:enumeration value="AL"/>
                        <xs:enumeration value="UAL"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="rooms">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                        <xs:minInclusive value="1"/>
                        <xs:maxInclusive value="5"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="condition" type="xs:boolean"/>
            <xs:element name="tv" type="xs:boolean"/>
            <xs:element name="wifi" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Wellness">
        <xs:complexContent>
            <xs:extension base="Voucher">
                <xs:sequence>
                    <xs:element name="drugs">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="pills"/>
                                <xs:enumeration value="injections"/>
                                <xs:enumeration value="Supplements"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="procedures">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="massage"/>
                                <xs:enumeration value="gymnastics"/>
                                <xs:enumeration value="physiotherapy"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="Entertaiment">
        <xs:complexContent>
            <xs:extension base="Voucher">
                <xs:sequence>
                    <xs:element name="bar">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="alcohol"/>
                                <xs:enumeration value="bowling"/>
                                <xs:enumeration value="billiards"/>
                                <xs:enumeration value="slots"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

</xs:schema>

=== Gleb-Turchik/XML_XSD_WebApp/web/resources/voucher.xml
<?xml version="1.0" encoding="UTF-8"?>
<tourist-vouchers
        xmlns="http://www.w3schools.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.w3schools.com voucher.xsd">

    <wellness-voucher id="1" name="Tenerife for rich">
        <type>weekend</type>
        <country>Spain</country>
        <number-days-nights>14</number-days-nights>
        <transport>air</transport>
        <hotel-characs>
            <stars>5</stars>
            <meal>true</meal>
            <kind-of-meal>UAL</kind-of-meal>
            <rooms>3</rooms>
            <condition>true</condition>
            <tv>true</tv>
            <wifi>true</wifi>
        </hotel-characs>
        <cost>3000</cost>
        <drugs>pills</drugs>
        <procedures>physiotherapy</procedures>
    </wellness-voucher>

    <wellness-voucher id="2" name="Madagascar">
        <type>relax</type>
        <country>Ecuador</country>
        <number-days-nights>11</number-days-nights>
        <transport>liner</transport>
        <hotel-characs>
            <stars>4</stars>
            <meal>true</meal>
            <kind-of-meal>HB+</kind-of-meal>
            <rooms>2</rooms>
            <condition>true</condition>
            <tv>false</tv>
            <wifi>true</wifi>
        </hotel-characs>
        <cost>5000</cost>
        <drugs>Supplements</drugs>
        <procedures>massage</procedures>
    </wellness-voucher>

    <wellness-voucher id="3" name="Abu-Dhabi">
        <type>pilgrimage</type>
        <country>United Arab Emirates</country>
        <number-days-nights>21</number-days-nights>
        <transport>car</transport>
        <hotel-characs>
            <stars>5</stars>
            <meal>true</meal>
            <kind-of-meal>UAL</kind-of-meal>
            <rooms>5</rooms>
            <condition>true</condition>
            <tv>true</tv>
            <wifi>true</wifi>
        </hotel-characs>
        <cost>4000</cost>
        <drugs>Supplements</drugs>
        <procedures>massage</procedures>
    </wellness-voucher>

    <wellness-voucher id="4" name="GOA">
        <type>tour</type>
        <country>India</country>
        <number-days-nights>7</number-days-nights>
        <transport>air</transport>
        <hotel-characs>
            <stars>2</stars>
            <meal>false</meal>
            <kind-of-meal>false</kind-of-meal>
            <rooms>1</rooms>
            <condition>true</condition>
            <tv>false</tv>
            <wifi>true</wifi>
        </hotel-characs>
        <cost>3000</cost>
        <drugs>pills</drugs>
        <procedures>physiotherapy</procedures>
    </wellness-voucher>

    <wellness-voucher id="5" name="Vityaz">
        <type>relax</type>
        <country>Gomel</country>
        <number-days-nights>7</number-days-nights>
        <transport>rail</transport>
        <hotel-characs>
            <stars>2</stars>
            <meal>true</meal>
            <kind-of-meal>BB</kind-of-meal>
            <rooms>2</rooms>
            <condition>false</condition>
            <tv>true</tv>
            <wifi>false</wifi>
        </hotel-characs>
        <cost>500</cost>
        <drugs>pills</drugs>
        <procedures>physiotherapy</procedures>
    </wellness-voucher>

    <wellness-voucher id="6" name="Alenka">
        <type>pilgrimage</type>
        <country>RU</country>
        <number-days-nights>11</number-days-nights>
        <transport>car</transport>
        <hotel-characs>
            <stars>2</stars>
            <meal>true</meal>
            <kind-of-meal>FB</kind-of-meal>
            <rooms>3</rooms>
            <condition>true</condition>
            <tv>true</tv>
            <wifi>true</wifi>
        </hotel-characs>
        <cost>1000</cost>
        <drugs>injections</drugs>
        <procedures>gymnastics</procedures>
    </wellness-voucher>

    <wellness-voucher id="7" name="Bora-Bora">
        <type>weekend</type>
        <country>Fr</country>
        <number-days-nights>14</number-days-nights>
        <transport>air</transport>
        <hotel-characs>
            <stars>5</stars>
            <meal>true</meal>
            <kind-of-meal>UAL</kind-of-meal>
            <rooms>3</rooms>
            <condition>true</condition>
            <tv>true</tv>
            <wifi>true</wifi>
        </hotel-characs>
        <cost>3000</cost>
        <drugs>pills</drugs>
        <procedures>physiotherapy</procedures>
    </wellness-voucher>

    <entertaiment-voucher id="8" name="Bora-Bora">
        <type>relax</type>
        <country>FR</country>
        <number-days-nights>14</number-days-nights>
        <transport>liner</transport>
        <hotel-characs>
            <stars>5</stars>
            <meal>true</meal>
            <kind-of-meal>UAL</kind-of-meal>
            <rooms>3</rooms>
            <condition>true</condition>
            <tv>true</tv>
            <wifi>true</wifi>
        </hotel-characs>
        <cost>2000</cost>
        <bar>alcohol</bar>
    </entertaiment-voucher>

    <entertaiment-voucher id="9" name="Italy for romantics">
        <type>tour</type>
        <country>Italy</country>
        <number-days-nights>11</number-days-nights>
        <transport>air</transport>
        <hotel-characs>
            <stars>4</stars>
            <meal>true</meal>
            <kind-of-meal>HB</kind-of-meal>
            <rooms>2</rooms>
            <condition>true</condition>
            <tv>false</tv>
            <wifi>true</wifi>
        </hotel-characs>
        <cost>2000</cost>
        <bar>billiards</bar>
    </entertaiment-voucher>

    <entertaiment-voucher id="10">
        <type>pilgrimage</type>
        <country>Italy</country>
        <number-days-nights>4</number-days-nights>
        <transport>car</transport>
        <hotel-characs>
            <stars>3</stars>
            <meal>true</meal>
            <kind-of-meal>AL</kind-of-meal>
            <rooms>1</rooms>
            <condition>true</condition>
            <tv>false</tv>
            <wifi>true</wifi>
        </hotel-characs>
        <cost>2000</cost>
        <bar>slots</bar>
    </entertaiment-voucher>

    <entertaiment-voucher id="11" name="Madagascar">
        <type>tour</type>
        <country>Africa</country>
        <number-days-nights>20</number-days-nights>
        <transport>liner</transport>
        <hotel-characs>
            <stars>3</stars>
            <meal>true</meal>
            <kind-of-meal>HB</kind-of-meal>
            <rooms>3</rooms>
            <condition>true</condition>
            <tv>false</tv>
            <wifi>false</wifi>
        </hotel-characs>
        <cost>3000</cost>
        <bar>alcohol</bar>
    </entertaiment-voucher>

    <entertaiment-voucher id="12">
        <type>tour</type>
        <country>Germany</country>
        <number-days-nights>11</number-days-nights>
        <transport>air</transport>
        <hotel-characs>
            <stars>4</stars>
            <meal>true</meal>
            <kind-of-meal>HB</kind-of-meal>
            <rooms>2</rooms>
            <condition>true</condition>
            <tv>false</tv>
            <wifi>true</wifi>
        </hotel-characs>
        <cost>1000</cost>
        <bar>bowling</bar>
    </entertaiment-voucher>

    <entertaiment-voucher id="13">
        <type>tour</type>
        <country>RU</country>
        <number-days-nights>4</number-days-nights>
        <transport>car</transport>
        <hotel-characs>
            <stars>2</stars>
            <meal>false</meal>
            <kind-of-meal>false</kind-of-meal>
            <rooms>2</rooms>
            <condition>true</condition>
            <tv>false</tv>
            <wifi>true</wifi>
        </hotel-characs>
        <cost>500</cost>
        <bar>alcohol</bar>
    </entertaiment-voucher>

    <entertaiment-voucher id="14">
        <type>tour</type>
        <country>Italy</country>
        <number-days-nights>4</number-days-nights>
        <transport>liner</transport>
        <hotel-characs>
            <stars>4</stars>
            <meal>true</meal>
            <kind-of-meal>HB</kind-of-meal>
            <rooms>2</rooms>
            <condition>true</condition>
            <tv>false</tv>
            <wifi>true</wifi>
        </hotel-characs>
        <cost>2000</cost>
        <bar>alcohol</bar>
    </entertaiment-voucher>

</tourist-vouchers>
